# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_client:
    docker:
      - image: circleci/node:latest
    working_directory: ~/code
    steps:
      - checkout
      - run: npm --prefix client install
      - run: npm --prefix client test
      - save_cache:
          key: repo-client-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

  build_server:
    docker:
      - image: circleci/node:latest
    working_directory: ~/code
    steps:
      - checkout
      - run: npm --prefix server install
      - run: npm --prefix server test
      - save_cache:
          key: repo-server-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

workflows:
  version: 2
  build-and-deploy-client:
    jobs:
      - build_client
      - build_server
      - deploy_client:
          requires:
            - build_client
          filters:
            branches:
              only:
                - master
                - develop
      - deploy_server:
          requires:
            - build_server
          filters:
            branches:
              only:
                - master
                - develop
